spring.application.name=SpringBootEncryptedLogsApplication

logging.file.path=logs
#logging.file.name=${logging.file.path}/encrypted-log.txt

#explicitly telling Spring Boot where to find log4j2.xml:
logging.config=classpath:log4j2.xml
